### PR TITLE
Make `useGlobalLeaflet` a prop of `LMap` only, and provide it for use in all child components

### LINKED ISSUE #118: Enabling useGlobalLeaflet breaks LCircle
I played around trying to get `leaflet-editable` working with the new `useGlobalLeaflet` option.

What I found is that it breaks `LCircle`.
To reproduce enable `useGlobalLeaflet` and place an `LCircle`

```
<l-map
    :center="mapOptions.center"
    :options="mapOptions"
    :zoom="mapOptions.zoom"
    >
            <l-circle :lat-lng="[0.0, 0.0]" :radius="2500" :fill="true"></l-circle>
</l-map>
```

The resulting error in the browser:
```
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Unhandled error during execution of mounted hook 
  at <LCircle lat-lng= (2) [0, 0] radius=2500 fill=true > 
  at <LMap center= LatLng {lat: 0, lng: 0} options= {zoomControl: false, maxZoom: 19, minZoom: 3, useGlobalLeaflet: true, zoom: 8, …} zoom=8  ... > 
  at <MapWrapper id="map-wrapper" class="is-flex-grow-5" > 
  at <Plan onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>
[...]
leaflet-src.js?e11e:1048 Uncaught (in promise) TypeError: Cannot read property 'x' of undefined
    at Proxy.intersects (leaflet-src.js?e11e:1048)
    at Proxy._empty (leaflet-src.esm.js?6bb3:7958)
    at Proxy._updateCircle (leaflet-src.js?e11e:12888)
    at Proxy._updatePath (leaflet-src.esm.js?6bb3:7954)
    at Proxy._update (leaflet-src.esm.js?6bb3:7949)
    at Proxy._reset (leaflet-src.esm.js?6bb3:7861)
    at Proxy.onAdd (leaflet-src.esm.js?6bb3:7806)
    at Proxy._layerAdd (leaflet-src.esm.js?6bb3:6561)
    at Proxy.whenReady (leaflet-src.js?e11e:4428)
    at Proxy.addLayer (leaflet-src.js?e11e:6629)
```

### PR DESCRIPTION
**Pull request by mikeu**
The current implementation of the `useGlobalLeaflet` option is available independently on every component through the `options` prop defined in `component.js`, yet only the `LMap` component makes any use of it. This means that a map created using `window.L.map` will contain layers, markers, etc., created by methods imported from the Leaflet ESM, which leads to the same errors described in [the readme](https://github.com/vue-leaflet/vue-leaflet/blob/63f6e4070c0049b9025ec627d06fa3f8d47333e2/README.md#working-with-leaflet) when `useGlobalLeaflet` is false but additional components are imported directly from `"leaflet"`. In particular, #118 is caused by having `LMap` imported from `"leaflet"` and `LCircle` imported from `"leaflet/dist/leaflet-src.esm.js"`.

Additionally, the `options` object is supposed to contain Leaflet configuration options to be passed directly to the Leaflet component factory, whereas `useGlobalLeaflet` is a property specific to the vue-leaflet components and shouldn't be passed on. So configuring the vue-leaflet component via a property on the Leaflet options object seems potentially worth reworking even without the above problem it's causing.

This PR resolved that discrepancy and fixes #118 by moving `useGlobalLeaflet` to be a prop of the `LMap` component (and at the same time removing it as an option on all other components). The map then `provide`s the property value, and every remaining component `inject`s that value, and imports its Leaflet requirements from the same Leaflet instance that the map containing it used based on that.

## Breaking change
This does mean that there is a **breaking change** here, because `<l-map :options="{ useGlobalLeaflet: true }" ...>` will no longer have any effect. However, since the effect it used to have led to the inability to use some of the remaining map components and we are still in pre-release, I think the change to `<l-map :useGlobalLeaflet="true" ...>` is acceptable, and even beneficial. Happy to hear alternative suggestions though!

## Discussion
cc @schmic as the reporter of #118, and @juan267 who introduced the original fix to allow the global Leaflet instance to be used by plugins.

I've tested this with the `LCircle` component in the original issue report as well as with a third-party vanilla Leaflet library that relies on the existence of `window.L`. But I haven't checked it out in an SSR scenario, or with the Geoman plugin that originally motivated this fix in #35, for instance. If anyone is able to further test those, or identify any potential problems, please let us know any comments or concerns with this PR, whether it works for you, etc.

### CODE REVIEW

File: src/components/LCircle.vue [hunk 1]
```diff
@@ -14,12 +19,15 @@ export default {
...
 
+    const useGlobalLeaflet = inject(GLOBAL_LEAFLET_OPT);
     const addLayer = inject("addLayer");
 
     const { options, methods } = circleSetup(props, leafletRef, context);
 
     onMounted(async () => {
-      const { circle, DomEvent } = await import("leaflet/dist/leaflet-src.esm");
+      const { circle, DomEvent } = useGlobalLeaflet
+        ? WINDOW_OR_GLOBAL.L
```
Comment (DonNicoJs) [inline src/components/LCircle.vue:29]: @mikeu Did we check if like this we break tree-shaking? I have a felling we do, we should maybe import this dynamically

**Comment by DonNicoJs** [comment]
@mikeu Thank you for working on this, and everything else you do for the repo while I am almost completely unavailable, I've left a question for you!

File: src/components/LCircle.vue (hunk 1 above)
Comment (mikeu) [reply src/components/LCircle.vue:29]: @DonNicoJs that is a good question that I haven't checked into yet, no.

Are you worried that this change will break tree shaking in general, even when `useGlobalLeaflet` is _not_ true? If so, then that is definitely an issue that will need further investigation.

I am not sure why you're worried about right here in particular though. Running `const { circle } = L` shouldn't really have anything to do with tree shaking, should it? It will simply execute as expected if that `L` already exists, or throw an error if it doesn't. The code here is basically the same as what [already exists in master](https://github.com/vue-leaflet/vue-leaflet/blob/8433a8986ac8c95ca091f4eaaadace8438cfc047/src/components/LMap.vue#L229-L231) in the LMap component, just without the conditional asynchronous import if the global variable isn't set.

What your question has now made me somewhat more worried about though is the [behaviour in LMap](https://github.com/vue-leaflet/vue-leaflet/pull/125/files/2b33787ab8cf2f0b1c29149017bde7833188190d#diff-c062e5b98deef6d3ca2604206fe64f4ac3a74887e252285b8559ee1e08e1b932R225-R227). Perhaps the fact that it has that `await import("leaflet")` even conditionally is enough to break tree shaking, which may very well not be able to identify whether `WINDOW_OR_GLOBAL.L` will be defined, and so might _always_ include the whole Leaflet package in the bundle...

If that's the case, then we should remove those lines and simply make it the responsibility of the user to guarantee that `L` will be globally defined before the map mounts if they choose to set `useGlobalLeaflet=true`, perhaps with a friendly error message if they haven't.

Do you happen to already have an environment set up to quickly test the results of tree shaking? Also, we've been speaking of "tree shaking" as a single unified feature that we intend to support, but is that a fair statement or do different algorithms mean we have to explicitly know whether the library works with tree shaking under Webpack, Rollup, esbuild, ...?

**Comment by juan267** [comment]
@mikeu @DonNicoJs

I tested this branch with Geoman and its working perfectly! Actually I was having issues with the current code on `master` and they all good fix with this changes. big 👍 for merging this PR

@mikeu thanks a lot for this!

**Review by DonNicoJs — APPROVED** [review]

**Comment by DazDotOne** [comment]
@juan267 
> I tested this branch with Geoman and its working perfectly! Actually I was having issues with the current code on `master` and they all good fix with this changes. big 👍 for merging this PR

You wouldn't happen have a simple example of how you got geoman and vue-leaflet working together would you? I'm struggling to get my head around the imports.
