### PR TITLE
fix: import icons with dynamic import and not require

### LINKED ISSUE #57: vue-leaflet doesn't work when built with Vite
### Bug description

When building a Vue app with **Vite**, the following error is displayed in the browser's console as soon as the LMap component is created:
```
Uncaught (in promise) ReferenceError: require is not defined
    at resetWebpackIcon (vue-leaflet.js:68)
    at vue-leaflet.js:1085
```
### How to reproduce
Run:
```sh
npm init vite-app temp --template vue
cd temp
npm i
npm i leaflet @vue-leaflet/vue-leaflet
```
Put the following code into *src/App.vue*:
```vue
<template>
  <l-map/>
</template>
<script>
import {LMap} from "@vue-leaflet/vue-leaflet"
export default {components: {LMap}}
</script>
```
Then run `npm run dev` and open the app in the browser.

### PR DESCRIPTION
**Pull request by DonNicoJs**
fixes #57 

Since we are using `import()` already everywhere we should not mix it with `require`, fixed it.

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@mikeu WDYT of this?

File: src/utils.js [hunk 1]
```diff
@@ -65,13 +65,19 @@ export const remapEvents = (contextAttrs) => {
   return result;
 };
 
-export const resetWebpackIcon = (Icon) => {
+export const resetWebpackIcon = async (Icon) => {
```
Comment (mikeu) [inline src/utils.js:68]: Is this functionality directly related to webpack? If we want/need to run it even when not using webpack, then should it maybe be named differently, and if we _don't_, then should there be some sort of check to try to detect whether webpack is being used? Not sure what that would look like, just raising the question...

**Review by mikeu — APPROVED** [review]
Other than the minor question of a possible name change, LGTM!

File: src/utils.js (hunk 1 above)
Comment (DonNicoJs) [reply src/utils.js:68]: @mikeu in a sense yes, it address a webpack bug, I think there is no harm in running this regardless of webpack (as I am aware) I think we can move on with this and then see if we get any issue / reports!
